<?php

namespace AdirKuhn\PatoCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends EntityRepository
{
}
