cash_flow:
    resource: "@CashFlowBundle/Resources/config/routing.yml"
    prefix:   /cashflow

clients:
    resource: "@ClientsBundle/Resources/config/routing.yml"
    prefix:   /clients

pato_core:
    resource: "@PatoCoreBundle/Resources/config/routing.yml"
    prefix:   /