<?php

namespace AdirKuhn\ClientsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function findCompanyByName($name)
    {
        //Native MySQL Query
        $dbalConn = $this->getEntityManager()->getConnection();

        $query = $dbalConn->query("
            SELECT * FROM company
            WHERE name LIKE '%". $name ."%'
        ");

        return $query->fetchAll();
    }
}
