<?php

namespace AdirKuhn\ClientsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findContactByName($name)
    {
        //Native MySQL Query
        $dbalConn = $this->getEntityManager()->getConnection();

        $query = $dbalConn->query("
            SELECT * FROM Contact
            WHERE name LIKE '%". $name ."%'
        ");

        return $query->fetchAll();
    }

    public function findRecentContacts()
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT c FROM ClientsBundle:Contact as c
                ORDER BY c.id DESC
            ")
            ->setMaxResults(10)
            ->getResult();
    }
}
