<?php

namespace AdirKuhn\CashFlowBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CashFlowItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashFlowItemRepository extends EntityRepository
{

    //find all cashflowitem + accounts
    public function findAllCashFlow($year, $month)
    {
        $dtStart = $year . '-' . $month . '-01';
        $dtEnd = $year . '-' . $month . '-31';

        //Native MySQL Query
        $dbalConn = $this->getEntityManager()->getConnection();

        $query = $dbalConn->query("
            SELECT * FROM cashflow
            WHERE paidAt BETWEEN '{$dtStart}' AND '{$dtEnd}'
        ");

        return $query->fetchAll();

    }

    /**
     * Get year with cashflow items
     *
     * @author Adir Kuhn <adirkuhn@gmail.com>
     *
     * @return array Years with cashflow Items
     */
    public function getCashFlowYearsWithAllAccounts()
    {
        //Native MySQL Query
        $dbalConn = $this->getEntityManager()->getConnection();

        $query = $dbalConn->query("
            SELECT DISTINCT
                SUBSTRING(paidAt, 1, 4) as year
            FROM
                cashflow
            WHERE
                paidAt IS NOT NULL
            GROUP BY year
        ");

        return $query->fetchAll();
    }

    /**
     * Get Balance for month and year
     *
     * @author Adir Kuhn <adirkuhn@gmail.com>
     *
     * return array Balance for month and year
     */
    public function getBalance($year, $month)
    {
        $dtStart = $year . '-' . $month . '-01';
        $dtEnd = $year . '-' . $month . '-31';

        $dbalConn = $this->getEntityManager()->getConnection();

        $query = $dbalConn->query("
            SELECT
              (sum(MonthBalancePositive) - sum(MonthBalanceNegative)) as MonthBalance,
              (sum(YearBalancePositive) - sum(YearBalanceNegative)) as YearBalance
            FROM
              (SELECT IF(ISNULL(SUM(value)), 0, SUM(value)) as MonthBalancePositive FROM cashflow WHERE status = 0 AND type = 0 AND paidAt BETWEEN '{$dtStart}' AND '{$dtEnd}') AS c,
              (SELECT IF(ISNULL(SUM(value)), 0, SUM(value)) as MonthBalanceNegative FROM cashflow WHERE status = 0 AND type = 1 AND paidAt BETWEEN '{$dtStart}' AND '{$dtEnd}') AS ca,
              (SELECT IF(ISNULL(SUM(value)), 0, SUM(value)) as YearBalancePositive FROM cashflow WHERE status = 0 AND type = 0 AND YEAR(paidAt) = '{$year}') AS cb,
              (SELECT IF(ISNULL(SUM(value)), 0, SUM(value)) as YearBalanceNegative FROM cashflow WHERE status = 0 AND type = 1 AND YEAR(paidAt) = '{$year}') AS cc
        ");

        return $query->fetchAll();
    }
}
