cash_flow_cashflow:
    resource: "@CashFlowBundle/Resources/config/routing/cashflowitem.yml"
    prefix:   /cashflow

cashflow_accounts_receivable:
    resource: "@CashFlowBundle/Resources/config/routing/accountsReceivable.yml"
    prefix:   /accounts/receivable

cashflow_accounts_payable:
    resource: "@CashFlowBundle/Resources/config/routing/accountsPayable.yml"
    prefix:   /accounts/payable

cashflow_homepage:
    path:     /
    defaults: { _controller: CashFlowBundle:Default:index }

cashflow_account_json_info:
    path: /accounts/info/{type}/{id}
    defaults: { _controller: "CashFlowBundle:Accounts:info", type:0, id:0 }
    requirements:
        type: \d+
        id: \d+