cashflow_accounts_receivable_home:
    path:     /
    defaults: { _controller: "CashFlowBundle:Accounts:index", selectedMonth: 0, selectedYear:0 }
cashflow_accounts_receivable_home_2:
    path:     /{selectedYear}/{selectedMonth}
    defaults: { _controller: "CashFlowBundle:Accounts:index", selectedMonth: 0, selectedYear:0 }
    requirements:
        selectedYear: \d+
        selectedMonth: \d+

cashflow_accounts_receivable_show:
    path:     /{id}/show
    defaults: { _controller: "CashFlowBundle:Accounts:show" }

cashflow_accounts_receivable_new:
    path:     /new
    defaults: { _controller: "CashFlowBundle:Accounts:new" }

cashflow_accounts_receivable_create:
    path:     /create
    defaults: { _controller: "CashFlowBundle:Accounts:create" }
    requirements: { _method: post }

cashflow_accounts_receivable_edit:
    path:     /{id}/edit
    defaults: { _controller: "CashFlowBundle:Accounts:edit" }

cashflow_accounts_receivable_update:
    path:     /{id}/update
    defaults: { _controller: "CashFlowBundle:Accounts:update" }
    requirements: { _method: post|put }

cashflow_accounts_receivable_delete:
    path:     /{id}/delete
    defaults: { _controller: "CashFlowBundle:Accounts:delete" }
    requirements: { _method: post|delete }
