AdirKuhn\PatoCoreBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AdirKuhn\PatoCoreBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        isActive:
            type: boolean
            options:
                default: true
        isAdmin:
            type: boolean
            options:
                default: false

    oneToMany:
        roles:
            targetEntity: Roles
            mappedBy: user
    lifecycleCallbacks: {  }
